name 'fatmcgav-glassfish'
version '0.1.0'

author 'Gavin Williams'
license 'GPLv3'
project_page 'http://github.com/fatmcgav/fatmcgav-glassfish'
source 'git://github.com/fatmcgav/fatmcgav-glassfish.git'
summary 'Module to manage Glassfish J2EE Application server, including installation and configuration. '
description ''
dependency 'puppetlabs-stdlib', '>=3.2.0'
