name 'fatmcgav-glassfish'
version '0.1.1'

author 'Gavin Williams'
license 'GPLv3'
project_page 'http://github.com/fatmcgav/puppet-glassfish'
source 'git://github.com/fatmcgav/puppet-glassfish.git'
summary 'A resource type to manage Glassfish domains, system-properties, jdbc-connection-pools and jdbc-resources and application deployment.'
description 'A resource type to manage Glassfish domains, system-properties, jdbc-connection-pools and jdbc-resources and application deployment.'
dependency 'puppetlabs/apt', '>=1.0.1'
dependency 'softek/java7', '>=0.1.0'
