name 'wavesoftware-glassfish'
version '0.4.0'

author 'Krzysztof Suszyński'
license 'GPLv3'
project_page 'http://github.com/wavesoftware/puppet-glassfish'
source 'git://github.com/wavesoftware/puppet-glassfish.git'
summary 'A plugin to manage Glassfish instalation and domains, system-properties, jdbc-connection-pools and jdbc-resources and application deployment.'
description 'This plugin for Puppet installs Glassfish Application Server and adds resource types and providers for managing Glassfish domains, system-properties, jdbc-connection-pools, jdbc-resources, custom-resources, auth-realms and application deployment by using the asadmin command line tool. This plugin uses the executable `asadmin` of Glassfish instalation. Plugin installs Glassfish in version `3.1.2.2` as standard and using `java-7-oracle` (also supports other JDK versions: `java-7-oracle`, `java-7-openjdk`, `java-6-oracle`, `java-6-openjdk`). It will also starts it as a service.'
dependency 'puppetlabs/apt', '>=1.0.1'
dependency 'softek/java7', '>=0.1.0'
